title: "Alex's Infosec Blog"
description: "Documenting my cybersecurity journey."
baseurl: "" 
url: "https://alex-infosec.github.io"
theme: jekyll-theme-cayman
paginate: 10
markdown: kramdown
highlighter: rouge