title: "Alex's Infosec Blog"
description: "Documenting my cybersecurity journey."
baseurl: "" 
url: "https://alex-infosec.github.io"
remote_theme: pages-themes/minimal@v0.2.0

# Markdown and Highlighter
markdown: kramdown
highlighter: rouge

# Pagination and Permalink
paginate: 10
paginate_path: "/page:num"
permalink: pretty

# Directories
source: .
destination: ./_site
layouts_dir: _layouts
data_dir: _data
includes_dir: _includes
sass:
  sass_dir: _sass

# Collections
collections:
  posts:
    output: true

# Exclude files you don’t want to publish
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - README.md

# Plugins (leave empty if not using any custom plugins)
plugins: 
  - jekyll-remote-theme

# Kramdown Settings
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  toc_levels: [1, 2, 3, 4, 5, 6]
